---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root 
  tasks:
    - name: Start container
      docker_container:
        name: "petclinic-{{ env | default('ci') }}"
        image: "qeqoos/spring-petclinic:{{ tag | default('latest') }}"
        state: started
        published_ports:
          - "{{ needed_port | default(80) }}:80"
