---
# aws ec2 ansible dynamic inventory plugin
plugin: aws_ec2

regions: 
  # - us-east-1
  - eu-west-1

strict: False

keyed_groups:
  #  each aws ec2 instance has it own instance tags. create  
  #  a tag variable from those tags for ansible to use. 
  #  if an EC2 tag:Name is acloudguru_machine, it'll be converted to the
  #  Ansible tag variable name as follows: tag_Name_acloudguru_machine
  # which can then be passed as a variable value for the host via -e flag
  - key: tags
    prefix: tag
  - key: tags.Applications
    separator: ''
  - key: instance_type
    prefix: aws_instance_type
  - key: placement.region
    prefix: aws_region
  - key: image_id
    prefix: aws_image


hostnames:
# a list in order of precedence for hostname variables.
# 
  - ip-address
  - dns-name
  - tag:Name