---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: Install dependencies
      yum:
        name: "{{ package }} "
        state: present
      vars:
        package:
        - wget
        - java-1.8.0-openjdk-devel.x86_64
        - git

    - name: install update
      yum: update_cache=yes

    - name: Install Docker
      shell: amazon-linux-extras install docker -y
    
    - name: Add ec2-user to docker group
      user:        
        name: "ec2-user"
        groups: docker
        append: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes